<?php

namespace Database\Seeders;

use App\Models\Extension;
use Illuminate\Database\Seeder;

class ExtensionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $jsonData = '{
            "data": [
                {
                    "id": "1",
                    "uid_no": "a7eee4d6-9105-4685-8eca-703c4fa758c0",
                    "account_id": "1",
                    "domain": "1",
                    "extension": "1000",
                    "password": "1000",
                    "voicemail_password": "1000",
                    "user": null,
                    "range": null,
                    "account_code": null,
                    "effectiveCallerIdName": null,
                    "effectiveCallerIdNumber": null,
                    "outbundCallerIdName": null,
                    "outbundCallerIdNumber": null,
                    "emergencyCallerIdName": null,
                    "emergencyCallerIdNumber": null,
                    "directoryFullname": null,
                    "directoryVisible": null,
                    "directoryExtensionVisible": "true",
                    "maxRegistration": null,
                    "limitMax": null,
                    "limitDestinations": null,
                    "voicemailEnabled": "N",
                    "voiceEmailTo": null,
                    "voiceMailFile": null,
                    "voiceMailkeepFile": "false",
                    "missedCall": "none",
                    "tollAllowValue": null,
                    "callTimeOut": null,
                    "callgroup": null,
                    "callScreen": "Disable",
                    "record": "A",
                    "description": null,
                    "callforward": "0",
                    "callforwardTo": null,
                    "onbusy": "0",
                    "onbusyTo": null,
                    "noanswer": "0",
                    "noanswerTo": null,
                    "notregistered": "0",
                    "notregisteredTo": null,
                    "dnd": "0",
                    "followme": "0",
                    "ignorebusy": "0",
                    "blockIncomingStatus": "0",
                    "blockOutGoingStatus": "0",
                    "created_by": "6",
                    "sofia_status": "0",
                    "deleted_at": null,
                    "created_at": "2024-06-06 09:57:29",
                    "updated_at": "2024-06-06 09:57:29"
                },
                {
                    "id": "2",
                    "uid_no": "7390d43a-3e3d-4558-b224-e811a4a8a5b5",
                    "account_id": "1",
                    "domain": "1",
                    "extension": "1001",
                    "password": "1001",
                    "voicemail_password": "1001",
                    "user": null,
                    "range": null,
                    "account_code": null,
                    "effectiveCallerIdName": null,
                    "effectiveCallerIdNumber": null,
                    "outbundCallerIdName": null,
                    "outbundCallerIdNumber": null,
                    "emergencyCallerIdName": null,
                    "emergencyCallerIdNumber": null,
                    "directoryFullname": null,
                    "directoryVisible": null,
                    "directoryExtensionVisible": "true",
                    "maxRegistration": null,
                    "limitMax": null,
                    "limitDestinations": null,
                    "voicemailEnabled": "N",
                    "voiceEmailTo": null,
                    "voiceMailFile": null,
                    "voiceMailkeepFile": "false",
                    "missedCall": "none",
                    "tollAllowValue": null,
                    "callTimeOut": null,
                    "callgroup": null,
                    "callScreen": "Disable",
                    "record": "A",
                    "description": null,
                    "callforward": "0",
                    "callforwardTo": null,
                    "onbusy": "0",
                    "onbusyTo": null,
                    "noanswer": "0",
                    "noanswerTo": null,
                    "notregistered": "0",
                    "notregisteredTo": null,
                    "dnd": "0",
                    "followme": "0",
                    "ignorebusy": "0",
                    "blockIncomingStatus": "0",
                    "blockOutGoingStatus": "0",
                    "created_by": "6",
                    "sofia_status": "0",
                    "deleted_at": null,
                    "created_at": "2024-06-06 09:57:44",
                    "updated_at": "2024-06-06 09:57:44"
                },
                {
                    "id": "3",
                    "uid_no": "7260fe8b-037d-4b96-ac02-99bf664e4d5e",
                    "account_id": "1",
                    "domain": "1",
                    "extension": "1002",
                    "password": "1002",
                    "voicemail_password": "1002",
                    "user": null,
                    "range": null,
                    "account_code": null,
                    "effectiveCallerIdName": null,
                    "effectiveCallerIdNumber": null,
                    "outbundCallerIdName": null,
                    "outbundCallerIdNumber": null,
                    "emergencyCallerIdName": null,
                    "emergencyCallerIdNumber": null,
                    "directoryFullname": null,
                    "directoryVisible": null,
                    "directoryExtensionVisible": "true",
                    "maxRegistration": null,
                    "limitMax": null,
                    "limitDestinations": null,
                    "voicemailEnabled": "N",
                    "voiceEmailTo": null,
                    "voiceMailFile": null,
                    "voiceMailkeepFile": "false",
                    "missedCall": "none",
                    "tollAllowValue": null,
                    "callTimeOut": null,
                    "callgroup": null,
                    "callScreen": "Disable",
                    "record": "A",
                    "description": null,
                    "callforward": "0",
                    "callforwardTo": null,
                    "onbusy": "0",
                    "onbusyTo": null,
                    "noanswer": "0",
                    "noanswerTo": null,
                    "notregistered": "0",
                    "notregisteredTo": null,
                    "dnd": "0",
                    "followme": "0",
                    "ignorebusy": "0",
                    "blockIncomingStatus": "0",
                    "blockOutGoingStatus": "0",
                    "created_by": "6",
                    "sofia_status": "1",
                    "deleted_at": null,
                    "created_at": "2024-06-06 09:57:53",
                    "updated_at": "2024-06-07 04:29:15"
                },
                {
                    "id": "4",
                    "uid_no": "8b4053c3-6d4c-4652-b1a9-754a08e239a1",
                    "account_id": "1",
                    "domain": "1",
                    "extension": "1003",
                    "password": "1003",
                    "voicemail_password": "1003",
                    "user": null,
                    "range": null,
                    "account_code": null,
                    "effectiveCallerIdName": null,
                    "effectiveCallerIdNumber": null,
                    "outbundCallerIdName": null,
                    "outbundCallerIdNumber": null,
                    "emergencyCallerIdName": null,
                    "emergencyCallerIdNumber": null,
                    "directoryFullname": null,
                    "directoryVisible": null,
                    "directoryExtensionVisible": "true",
                    "maxRegistration": null,
                    "limitMax": null,
                    "limitDestinations": null,
                    "voicemailEnabled": "N",
                    "voiceEmailTo": null,
                    "voiceMailFile": null,
                    "voiceMailkeepFile": "false",
                    "missedCall": "none",
                    "tollAllowValue": null,
                    "callTimeOut": null,
                    "callgroup": null,
                    "callScreen": "Disable",
                    "record": "A",
                    "description": null,
                    "callforward": "0",
                    "callforwardTo": null,
                    "onbusy": "0",
                    "onbusyTo": null,
                    "noanswer": "0",
                    "noanswerTo": null,
                    "notregistered": "0",
                    "notregisteredTo": null,
                    "dnd": "0",
                    "followme": "0",
                    "ignorebusy": "0",
                    "blockIncomingStatus": "0",
                    "blockOutGoingStatus": "0",
                    "created_by": "6",
                    "sofia_status": "1",
                    "deleted_at": null,
                    "created_at": "2024-06-06 09:58:02",
                    "updated_at": "2024-06-07 05:12:22"
                },
                {
                    "id": "5",
                    "uid_no": "1f42f853-07f8-4fbf-b90e-29216d223582",
                    "account_id": "1",
                    "domain": "1",
                    "extension": "1004",
                    "password": "1004",
                    "voicemail_password": "1004",
                    "user": null,
                    "range": null,
                    "account_code": null,
                    "effectiveCallerIdName": null,
                    "effectiveCallerIdNumber": null,
                    "outbundCallerIdName": null,
                    "outbundCallerIdNumber": null,
                    "emergencyCallerIdName": null,
                    "emergencyCallerIdNumber": null,
                    "directoryFullname": null,
                    "directoryVisible": null,
                    "directoryExtensionVisible": "true",
                    "maxRegistration": null,
                    "limitMax": null,
                    "limitDestinations": null,
                    "voicemailEnabled": "N",
                    "voiceEmailTo": null,
                    "voiceMailFile": null,
                    "voiceMailkeepFile": "false",
                    "missedCall": "none",
                    "tollAllowValue": null,
                    "callTimeOut": null,
                    "callgroup": null,
                    "callScreen": "Disable",
                    "record": "A",
                    "description": null,
                    "callforward": "0",
                    "callforwardTo": null,
                    "onbusy": "0",
                    "onbusyTo": null,
                    "noanswer": "0",
                    "noanswerTo": null,
                    "notregistered": "0",
                    "notregisteredTo": null,
                    "dnd": "0",
                    "followme": "0",
                    "ignorebusy": "0",
                    "blockIncomingStatus": "0",
                    "blockOutGoingStatus": "0",
                    "created_by": "6",
                    "sofia_status": "1",
                    "deleted_at": null,
                    "created_at": "2024-06-06 09:58:10",
                    "updated_at": "2024-06-07 05:13:01"
                },
                {
                    "id": "6",
                    "uid_no": "a1acd04c-b070-4a1b-9678-0ec1a2781bc9",
                    "account_id": "1",
                    "domain": "1",
                    "extension": "1005",
                    "password": "1005",
                    "voicemail_password": "1005",
                    "user": null,
                    "range": null,
                    "account_code": null,
                    "effectiveCallerIdName": null,
                    "effectiveCallerIdNumber": null,
                    "outbundCallerIdName": null,
                    "outbundCallerIdNumber": null,
                    "emergencyCallerIdName": null,
                    "emergencyCallerIdNumber": null,
                    "directoryFullname": null,
                    "directoryVisible": null,
                    "directoryExtensionVisible": "true",
                    "maxRegistration": null,
                    "limitMax": null,
                    "limitDestinations": null,
                    "voicemailEnabled": "N",
                    "voiceEmailTo": null,
                    "voiceMailFile": null,
                    "voiceMailkeepFile": "false",
                    "missedCall": "none",
                    "tollAllowValue": null,
                    "callTimeOut": null,
                    "callgroup": null,
                    "callScreen": "Disable",
                    "record": "A",
                    "description": null,
                    "callforward": "0",
                    "callforwardTo": null,
                    "onbusy": "0",
                    "onbusyTo": null,
                    "noanswer": "0",
                    "noanswerTo": null,
                    "notregistered": "0",
                    "notregisteredTo": null,
                    "dnd": "0",
                    "followme": "0",
                    "ignorebusy": "0",
                    "blockIncomingStatus": "0",
                    "blockOutGoingStatus": "0",
                    "created_by": "6",
                    "sofia_status": "1",
                    "deleted_at": null,
                    "created_at": "2024-06-06 09:58:19",
                    "updated_at": "2024-06-07 05:01:47"
                }
            ]
        }';

        $arrayData = json_decode($jsonData, true);

        $data = $arrayData['data'];

        $formattedData = [];

        foreach ($data as $row) {
            unset($row['id'], $row['uid_no'], $row['created_by'], $row['deleted_at'], $row['created_at'], $row['updated_at']);
            $row['created_by'] = 1;
            $row['created_at'] = date("Y-m-d H:i:s");
            $row['updated_at'] = date("Y-m-d H:i:s");
            $formattedData[] = $row;
        }

        Extension::insert($formattedData);
    }
}
