<?php

namespace Database\Seeders;

use App\Models\SipProfileSetting;
use Illuminate\Database\Seeder;

class SipProfileSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $jsonData = '{
            "data": [
                {
                    "id": "286",
                    "sip_profile_uuid": "1",
                    "name": "rtp-digit-delay",
                    "value": "40",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "287",
                    "sip_profile_uuid": "1",
                    "name": "media-option",
                    "value": "resume-media-on-hold",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "288",
                    "sip_profile_uuid": "1",
                    "name": "media-option",
                    "value": "bypass-media-after-att-xfer",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "289",
                    "sip_profile_uuid": "1",
                    "name": "user-agent-strin",
                    "value": "FreeSWITCH Rocks!",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "290",
                    "sip_profile_uuid": "1",
                    "name": "debug",
                    "value": "0",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "291",
                    "sip_profile_uuid": "1",
                    "name": "dshutdown-on-fail",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "292",
                    "sip_profile_uuid": "1",
                    "name": "sip-trace",
                    "value": "no",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "293",
                    "sip_profile_uuid": "1",
                    "name": "sip-capture",
                    "value": "no",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "294",
                    "sip_profile_uuid": "1",
                    "name": "presence-proto-lookup",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "295",
                    "sip_profile_uuid": "1",
                    "name": "liberal-dtmf",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "296",
                    "sip_profile_uuid": "1",
                    "name": "watchdog-enabled",
                    "value": "no",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "297",
                    "sip_profile_uuid": "1",
                    "name": "watchdog-step-timeout",
                    "value": "30000",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "298",
                    "sip_profile_uuid": "1",
                    "name": "watchdog-event-timeout",
                    "value": "30000",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "299",
                    "sip_profile_uuid": "1",
                    "name": "log-auth-failures",
                    "value": "false",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "300",
                    "sip_profile_uuid": "1",
                    "name": "forward-unsolicited-mwi-notify",
                    "value": "false",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "301",
                    "sip_profile_uuid": "1",
                    "name": "context",
                    "value": "public",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "302",
                    "sip_profile_uuid": "1",
                    "name": "rfc2833-pt",
                    "value": "101",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "303",
                    "sip_profile_uuid": "1",
                    "name": "sip-port",
                    "value": "$${internal_sip_port}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "304",
                    "sip_profile_uuid": "1",
                    "name": "dialplan",
                    "value": "XML",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "305",
                    "sip_profile_uuid": "1",
                    "name": "dtmf-duration",
                    "value": "2000",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "306",
                    "sip_profile_uuid": "1",
                    "name": "inbound-codec-prefs",
                    "value": "$${global_codec_prefs}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "307",
                    "sip_profile_uuid": "1",
                    "name": "outbound-codec-prefs",
                    "value": "$${global_codec_prefs}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "308",
                    "sip_profile_uuid": "1",
                    "name": "rtp-timer-name",
                    "value": "soft",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "309",
                    "sip_profile_uuid": "1",
                    "name": "rtp-ip",
                    "value": "$${local_ip_v4}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "310",
                    "sip_profile_uuid": "1",
                    "name": "sip-ip",
                    "value": "$${local_ip_v4}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "311",
                    "sip_profile_uuid": "1",
                    "name": "hold-music",
                    "value": "$${hold_music}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "312",
                    "sip_profile_uuid": "1",
                    "name": "apply-nat-acl",
                    "value": "nat.auto",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "313",
                    "sip_profile_uuid": "1",
                    "name": "csip_profile_uuid-in-1xx",
                    "value": "false",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "314",
                    "sip_profile_uuid": "1",
                    "name": "extended-info-parsing",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "315",
                    "sip_profile_uuid": "1",
                    "name": "aggressive-nat-detection",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "316",
                    "sip_profile_uuid": "1",
                    "name": "enable-100rel",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "317",
                    "sip_profile_uuid": "1",
                    "name": "disable-srv503",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "318",
                    "sip_profile_uuid": "1",
                    "name": "enable-compact-headers",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "319",
                    "sip_profile_uuid": "1",
                    "name": "enable-timer",
                    "value": "false",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "320",
                    "sip_profile_uuid": "1",
                    "name": "minimum-session-expires",
                    "value": "120",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "321",
                    "sip_profile_uuid": "1",
                    "name": "apply-inbound-acl",
                    "value": "domains",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "322",
                    "sip_profile_uuid": "1",
                    "name": "local-network-acl",
                    "value": "localnet.auto",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "323",
                    "sip_profile_uuid": "1",
                    "name": "apply-register-acl",
                    "value": "domains",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "324",
                    "sip_profile_uuid": "1",
                    "name": "dtmf-type",
                    "value": "info",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "325",
                    "sip_profile_uuid": "1",
                    "name": "send-message-query-on-register",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "326",
                    "sip_profile_uuid": "1",
                    "name": "send-presence-on-register",
                    "value": "first-only",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "327",
                    "sip_profile_uuid": "1",
                    "name": "caller-sip_profile_uuid-type",
                    "value": "rpsip_profile_uuid",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "328",
                    "sip_profile_uuid": "1",
                    "name": "caller-sip_profile_uuid-type",
                    "value": "psip_profile_uuid",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "329",
                    "sip_profile_uuid": "1",
                    "name": "caller-sip_profile_uuid-type",
                    "value": "none",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "330",
                    "sip_profile_uuid": "1",
                    "name": "record-path",
                    "value": "$${recordings_dir}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "331",
                    "sip_profile_uuid": "1",
                    "name": "record-template",
                    "value": "${caller_sip_profile_uuid_number}.${target_domain}.${strftime(%Y-%m-%d-%H-%M-%S)}.wav",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "332",
                    "sip_profile_uuid": "1",
                    "name": "manage-presence",
                    "value": "true",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "333",
                    "sip_profile_uuid": "1",
                    "name": "presence-probe-on-register",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "334",
                    "sip_profile_uuid": "1",
                    "name": "manage-shared-appearance",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "335",
                    "sip_profile_uuid": "1",
                    "name": "dbname",
                    "value": "share_presence",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "336",
                    "sip_profile_uuid": "1",
                    "name": "presence-hosts",
                    "value": "$${domain},$${local_ip_v4}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "337",
                    "sip_profile_uuid": "1",
                    "name": "presence-privacy",
                    "value": "$${presence_privacy}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "338",
                    "sip_profile_uuid": "1",
                    "name": "bitpacking",
                    "value": "aa12",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "339",
                    "sip_profile_uuid": "1",
                    "name": "max-proceeding",
                    "value": "1000",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "340",
                    "sip_profile_uuid": "1",
                    "name": "max-recv-requests-per-second",
                    "value": "0",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "341",
                    "sip_profile_uuid": "1",
                    "name": "session-timeout",
                    "value": "1800",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "342",
                    "sip_profile_uuid": "1",
                    "name": "multiple-registrations",
                    "value": "contact",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "343",
                    "sip_profile_uuid": "1",
                    "name": "inbound-codec-negotiation",
                    "value": "generous",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "344",
                    "sip_profile_uuid": "1",
                    "name": "bind-params",
                    "value": "transport=udp",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "345",
                    "sip_profile_uuid": "1",
                    "name": "unregister-on-options-fail",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "346",
                    "sip_profile_uuid": "1",
                    "name": "all-reg-options-ping",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "347",
                    "sip_profile_uuid": "1",
                    "name": "nat-options-ping",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "348",
                    "sip_profile_uuid": "1",
                    "name": "sip-options-respond-503-on-busy",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "349",
                    "sip_profile_uuid": "1",
                    "name": "sip-messages-respond-200-ok",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "350",
                    "sip_profile_uuid": "1",
                    "name": "sip-subscribe-respond-200-ok",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "351",
                    "sip_profile_uuid": "1",
                    "name": "tls",
                    "value": "$${internal_ssl_enable}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "352",
                    "sip_profile_uuid": "1",
                    "name": "tls-only",
                    "value": "false",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "353",
                    "sip_profile_uuid": "1",
                    "name": "tls-bind-params",
                    "value": "transport=tls",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "354",
                    "sip_profile_uuid": "1",
                    "name": "tls-sip-port",
                    "value": "$${internal_tls_port}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "355",
                    "sip_profile_uuid": "1",
                    "name": "tls-cert-dir",
                    "value": "",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "356",
                    "sip_profile_uuid": "1",
                    "name": "tls-passphrase",
                    "value": "",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "357",
                    "sip_profile_uuid": "1",
                    "name": "tls-verify-date",
                    "value": "true",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "358",
                    "sip_profile_uuid": "1",
                    "name": "tls-verify-policy",
                    "value": "none",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "359",
                    "sip_profile_uuid": "1",
                    "name": "tls-verify-depth",
                    "value": "2",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "360",
                    "sip_profile_uuid": "1",
                    "name": "tls-verify-in-subjects",
                    "value": "",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "361",
                    "sip_profile_uuid": "1",
                    "name": "tls-version",
                    "value": "$${sip_tls_version}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "362",
                    "sip_profile_uuid": "1",
                    "name": "tls-ciphers",
                    "value": "$${sip_tls_ciphers}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "363",
                    "sip_profile_uuid": "1",
                    "name": "tls-orq-connect-timeout",
                    "value": "3000",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "364",
                    "sip_profile_uuid": "1",
                    "name": "rtp-autoflush-during-brsip_profile_uuidge",
                    "value": "false",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "365",
                    "sip_profile_uuid": "1",
                    "name": "rtp-rewrite-timestamps",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "366",
                    "sip_profile_uuid": "1",
                    "name": "pass-rfc2833",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "367",
                    "sip_profile_uuid": "1",
                    "name": "odbc-dsn",
                    "value": "dsn:user:pass",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "368",
                    "sip_profile_uuid": "1",
                    "name": "odbc-dsn",
                    "value": "pgsql://hostaddr=127.0.0.1 dbname=freeswitch user=freeswitch password=\"\" options=\"-c client_min_messages=NOTICE\" application_name=\"freeswitch\"",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "369",
                    "sip_profile_uuid": "1",
                    "name": "odbc-dsn",
                    "value": "mariadb://Server=192.168.1.88;Database=internal;Usip_profile_uuid=freeswitch;Pwd=freeswitch;",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "370",
                    "sip_profile_uuid": "1",
                    "name": "db-spin-up-wait-ms",
                    "value": "1000",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "371",
                    "sip_profile_uuid": "1",
                    "name": "inbound-bypass-media",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "372",
                    "sip_profile_uuid": "1",
                    "name": "inbound-proxy-media",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "373",
                    "sip_profile_uuid": "1",
                    "name": "inbound-late-negotiation",
                    "value": "true",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "374",
                    "sip_profile_uuid": "1",
                    "name": "accept-blind-reg",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "375",
                    "sip_profile_uuid": "1",
                    "name": "accept-blind-auth",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "376",
                    "sip_profile_uuid": "1",
                    "name": "suppress-cng",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "377",
                    "sip_profile_uuid": "1",
                    "name": "nonce-ttl",
                    "value": "60",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "378",
                    "sip_profile_uuid": "1",
                    "name": "disable-transcoding",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "379",
                    "sip_profile_uuid": "1",
                    "name": "manual-redirect",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "380",
                    "sip_profile_uuid": "1",
                    "name": "disable-transfer",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "381",
                    "sip_profile_uuid": "1",
                    "name": "disable-register",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "382",
                    "sip_profile_uuid": "1",
                    "name": "NDLB-broken-auth-hash",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "383",
                    "sip_profile_uuid": "1",
                    "name": "NDLB-received-in-nat-reg-contact",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "384",
                    "sip_profile_uuid": "1",
                    "name": "auth-calls",
                    "value": "$${internal_auth_calls}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "385",
                    "sip_profile_uuid": "1",
                    "name": "auth-subscriptions",
                    "value": "true",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "386",
                    "sip_profile_uuid": "1",
                    "name": "inbound-reg-force-matching-username",
                    "value": "true",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "387",
                    "sip_profile_uuid": "1",
                    "name": "auth-all-packets",
                    "value": "false",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "388",
                    "sip_profile_uuid": "1",
                    "name": "ext-rtp-ip",
                    "value": "$${external_rtp_ip}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "389",
                    "sip_profile_uuid": "1",
                    "name": "ext-sip-ip",
                    "value": "$${external_sip_ip}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "390",
                    "sip_profile_uuid": "1",
                    "name": "rtp-timeout-sec",
                    "value": "300",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "391",
                    "sip_profile_uuid": "1",
                    "name": "rtp-hold-timeout-sec",
                    "value": "1800",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "392",
                    "sip_profile_uuid": "1",
                    "name": "vad",
                    "value": "in",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "393",
                    "sip_profile_uuid": "1",
                    "name": "vad",
                    "value": "out",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "394",
                    "sip_profile_uuid": "1",
                    "name": "vad",
                    "value": "both",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "395",
                    "sip_profile_uuid": "1",
                    "name": "alias",
                    "value": "sip:10.0.1.251:5555",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "396",
                    "sip_profile_uuid": "1",
                    "name": "force-register-domain",
                    "value": "$${domain}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "397",
                    "sip_profile_uuid": "1",
                    "name": "force-subscription-domain",
                    "value": "$${domain}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "398",
                    "sip_profile_uuid": "1",
                    "name": "force-register-db-domain",
                    "value": "$${domain}",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "399",
                    "sip_profile_uuid": "1",
                    "name": "ws-binding",
                    "value": ":5066",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "400",
                    "sip_profile_uuid": "1",
                    "name": "wss-binding",
                    "value": ":7443",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "401",
                    "sip_profile_uuid": "1",
                    "name": "delete-subs-on-register",
                    "value": "false",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "402",
                    "sip_profile_uuid": "1",
                    "name": "inbound-reg-in-new-thread",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "403",
                    "sip_profile_uuid": "1",
                    "name": "rtcp-audio-interval-msec",
                    "value": "5000",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "404",
                    "sip_profile_uuid": "1",
                    "name": "rtcp-vsip_profile_uuideo-interval-msec",
                    "value": "5000",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "405",
                    "sip_profile_uuid": "1",
                    "name": "force-subscription-expires",
                    "value": "60",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "406",
                    "sip_profile_uuid": "1",
                    "name": "sip-subscription-max-deviation",
                    "value": "120",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "407",
                    "sip_profile_uuid": "1",
                    "name": "disable-transfer",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "408",
                    "sip_profile_uuid": "1",
                    "name": "disable-register",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "409",
                    "sip_profile_uuid": "1",
                    "name": "enable-3pcc",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "410",
                    "sip_profile_uuid": "1",
                    "name": "NDLB-force-rport",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "411",
                    "sip_profile_uuid": "1",
                    "name": "challenge-realm",
                    "value": "auto_from",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "412",
                    "sip_profile_uuid": "1",
                    "name": "disable-rtp-auto-adjust",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "413",
                    "sip_profile_uuid": "1",
                    "name": "inbound-use-callsip_profile_uuid-as-uusip_profile_uuid",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "414",
                    "sip_profile_uuid": "1",
                    "name": "outbound-use-uusip_profile_uuid-as-callsip_profile_uuid",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "415",
                    "sip_profile_uuid": "1",
                    "name": "rtp-autofix-timing",
                    "value": "false",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "416",
                    "sip_profile_uuid": "1",
                    "name": "pass-callee-sip_profile_uuid",
                    "value": "false",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "417",
                    "sip_profile_uuid": "1",
                    "name": "auto-rtp-bugs",
                    "value": "clear",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "418",
                    "sip_profile_uuid": "1",
                    "name": "disable-srv",
                    "value": "false",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "419",
                    "sip_profile_uuid": "1",
                    "name": "disable-naptr",
                    "value": "false",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "420",
                    "sip_profile_uuid": "1",
                    "name": "timer-T1",
                    "value": "500",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "421",
                    "sip_profile_uuid": "1",
                    "name": "timer-T1X64",
                    "value": "32000",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "422",
                    "sip_profile_uuid": "1",
                    "name": "timer-T2",
                    "value": "4000",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "423",
                    "sip_profile_uuid": "1",
                    "name": "timer-T4",
                    "value": "4000",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "424",
                    "sip_profile_uuid": "1",
                    "name": "auto-jitterbuffer-msec",
                    "value": "60",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "425",
                    "sip_profile_uuid": "1",
                    "name": "renegotiate-codec-on-hold",
                    "value": "true",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "426",
                    "sip_profile_uuid": "1",
                    "name": "auto-invite-100",
                    "value": "false",
                    "enabled": "0",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                },
                {
                    "id": "427",
                    "sip_profile_uuid": "1",
                    "name": "odbc-dsn",
                    "value": "mariadb://Server=192.168.1.88;Database=internal;Uid=solman;Pwd=password;",
                    "enabled": "1",
                    "description": null,
                    "created_by": null,
                    "deleted_at": null,
                    "created_at": null,
                    "updated_at": null
                }
            ]
        }';

        // Convert JSON data to PHP associative array
        $arrayData = json_decode($jsonData, true);

        $data = $arrayData['data'];

        if ($arrayData === null) {
            echo "JSON decoding error: " . json_last_error_msg();
        }
        // dd($arrayData);
        // exit;

        $formattedData = [];

        foreach ($data as $row) {
            unset($row['id'], $row['created_by'], $row['deleted_at'], $row['created_at'], $row['updated_at']);
            $row['created_at'] = date("Y-m-d H:i:s");
            $row['updated_at'] = date("Y-m-d H:i:s");
            $formattedData[] = $row;
        }

        SipProfileSetting::insert($formattedData);
    }
}
