<?php

namespace Database\Seeders;

use App\Models\SipProfileSetting;
use Illuminate\Database\Seeder;

class SipProfileSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $jsonData = '{
            "data": [
              {
                "id": "1",
                "sip_profile_uuid": "1",
                "name": "rtp-digit-delay",
                "value": "40",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "2",
                "sip_profile_uuid": "1",
                "name": "media-option",
                "value": "resume-media-on-hold",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "3",
                "sip_profile_uuid": "1",
                "name": "media-option",
                "value": "bypass-media-after-att-xfer",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "4",
                "sip_profile_uuid": "1",
                "name": "user-agent-strin",
                "value": "FreeSWITCH Rocks!",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "5",
                "sip_profile_uuid": "1",
                "name": "debug",
                "value": "0",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "6",
                "sip_profile_uuid": "1",
                "name": "dshutdown-on-fail",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "7",
                "sip_profile_uuid": "1",
                "name": "sip-trace",
                "value": "no",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "8",
                "sip_profile_uuid": "1",
                "name": "sip-capture",
                "value": "no",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "9",
                "sip_profile_uuid": "1",
                "name": "presence-proto-lookup",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "10",
                "sip_profile_uuid": "1",
                "name": "liberal-dtmf",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "11",
                "sip_profile_uuid": "1",
                "name": "watchdog-enabled",
                "value": "no",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "12",
                "sip_profile_uuid": "1",
                "name": "watchdog-step-timeout",
                "value": "30000",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "13",
                "sip_profile_uuid": "1",
                "name": "watchdog-event-timeout",
                "value": "30000",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "14",
                "sip_profile_uuid": "1",
                "name": "log-auth-failures",
                "value": "false",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "15",
                "sip_profile_uuid": "1",
                "name": "forward-unsolicited-mwi-notify",
                "value": "false",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "16",
                "sip_profile_uuid": "1",
                "name": "context",
                "value": "public",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "17",
                "sip_profile_uuid": "1",
                "name": "rfc2833-pt",
                "value": "101",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "18",
                "sip_profile_uuid": "1",
                "name": "sip-port",
                "value": "$${internal_sip_port}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "19",
                "sip_profile_uuid": "1",
                "name": "dialplan",
                "value": "XML",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "20",
                "sip_profile_uuid": "1",
                "name": "dtmf-duration",
                "value": "2000",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "21",
                "sip_profile_uuid": "1",
                "name": "inbound-codec-prefs",
                "value": "$${global_codec_prefs}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "22",
                "sip_profile_uuid": "1",
                "name": "outbound-codec-prefs",
                "value": "$${global_codec_prefs}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "23",
                "sip_profile_uuid": "1",
                "name": "rtp-timer-name",
                "value": "soft",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "24",
                "sip_profile_uuid": "1",
                "name": "rtp-ip",
                "value": "$${local_ip_v4}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "25",
                "sip_profile_uuid": "1",
                "name": "sip-ip",
                "value": "$${local_ip_v4}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "26",
                "sip_profile_uuid": "1",
                "name": "hold-music",
                "value": "$${hold_music}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "27",
                "sip_profile_uuid": "1",
                "name": "apply-nat-acl",
                "value": "nat.auto",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "28",
                "sip_profile_uuid": "1",
                "name": "csip_profile_uuid-in-1xx",
                "value": "false",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "29",
                "sip_profile_uuid": "1",
                "name": "extended-info-parsing",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "30",
                "sip_profile_uuid": "1",
                "name": "aggressive-nat-detection",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "31",
                "sip_profile_uuid": "1",
                "name": "enable-100rel",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "32",
                "sip_profile_uuid": "1",
                "name": "disable-srv503",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "33",
                "sip_profile_uuid": "1",
                "name": "enable-compact-headers",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "34",
                "sip_profile_uuid": "1",
                "name": "enable-timer",
                "value": "false",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "35",
                "sip_profile_uuid": "1",
                "name": "minimum-session-expires",
                "value": "120",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "36",
                "sip_profile_uuid": "1",
                "name": "apply-inbound-acl",
                "value": "domains",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "37",
                "sip_profile_uuid": "1",
                "name": "local-network-acl",
                "value": "localnet.auto",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "38",
                "sip_profile_uuid": "1",
                "name": "apply-register-acl",
                "value": "domains",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "39",
                "sip_profile_uuid": "1",
                "name": "dtmf-type",
                "value": "info",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "40",
                "sip_profile_uuid": "1",
                "name": "send-message-query-on-register",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "41",
                "sip_profile_uuid": "1",
                "name": "send-presence-on-register",
                "value": "first-only",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "42",
                "sip_profile_uuid": "1",
                "name": "caller-sip_profile_uuid-type",
                "value": "rpsip_profile_uuid",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "43",
                "sip_profile_uuid": "1",
                "name": "caller-sip_profile_uuid-type",
                "value": "psip_profile_uuid",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "44",
                "sip_profile_uuid": "1",
                "name": "caller-sip_profile_uuid-type",
                "value": "none",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "45",
                "sip_profile_uuid": "1",
                "name": "record-path",
                "value": "$${recordings_dir}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "46",
                "sip_profile_uuid": "1",
                "name": "record-template",
                "value": "${caller_sip_profile_uuid_number}.${target_domain}.${strftime(%Y-%m-%d-%H-%M-%S)}.wav",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "47",
                "sip_profile_uuid": "1",
                "name": "manage-presence",
                "value": "true",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "48",
                "sip_profile_uuid": "1",
                "name": "presence-probe-on-register",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "49",
                "sip_profile_uuid": "1",
                "name": "manage-shared-appearance",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "50",
                "sip_profile_uuid": "1",
                "name": "dbname",
                "value": "share_presence",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "51",
                "sip_profile_uuid": "1",
                "name": "presence-hosts",
                "value": "$${domain},$${local_ip_v4}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "52",
                "sip_profile_uuid": "1",
                "name": "presence-privacy",
                "value": "$${presence_privacy}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "53",
                "sip_profile_uuid": "1",
                "name": "bitpacking",
                "value": "aa12",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "54",
                "sip_profile_uuid": "1",
                "name": "max-proceeding",
                "value": "1000",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "55",
                "sip_profile_uuid": "1",
                "name": "max-recv-requests-per-second",
                "value": "0",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "56",
                "sip_profile_uuid": "1",
                "name": "session-timeout",
                "value": "1800",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "57",
                "sip_profile_uuid": "1",
                "name": "multiple-registrations",
                "value": "contact",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "58",
                "sip_profile_uuid": "1",
                "name": "inbound-codec-negotiation",
                "value": "generous",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "59",
                "sip_profile_uuid": "1",
                "name": "bind-params",
                "value": "transport=udp",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "60",
                "sip_profile_uuid": "1",
                "name": "unregister-on-options-fail",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "61",
                "sip_profile_uuid": "1",
                "name": "all-reg-options-ping",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "62",
                "sip_profile_uuid": "1",
                "name": "nat-options-ping",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "63",
                "sip_profile_uuid": "1",
                "name": "sip-options-respond-503-on-busy",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "64",
                "sip_profile_uuid": "1",
                "name": "sip-messages-respond-200-ok",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "65",
                "sip_profile_uuid": "1",
                "name": "sip-subscribe-respond-200-ok",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "66",
                "sip_profile_uuid": "1",
                "name": "tls",
                "value": "$${internal_ssl_enable}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "67",
                "sip_profile_uuid": "1",
                "name": "tls-only",
                "value": "false",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "68",
                "sip_profile_uuid": "1",
                "name": "tls-bind-params",
                "value": "transport=tls",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "69",
                "sip_profile_uuid": "1",
                "name": "tls-sip-port",
                "value": "$${internal_tls_port}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "70",
                "sip_profile_uuid": "1",
                "name": "tls-cert-dir",
                "value": "",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "71",
                "sip_profile_uuid": "1",
                "name": "tls-passphrase",
                "value": "",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "72",
                "sip_profile_uuid": "1",
                "name": "tls-verify-date",
                "value": "true",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "73",
                "sip_profile_uuid": "1",
                "name": "tls-verify-policy",
                "value": "none",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "74",
                "sip_profile_uuid": "1",
                "name": "tls-verify-depth",
                "value": "2",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "75",
                "sip_profile_uuid": "1",
                "name": "tls-verify-in-subjects",
                "value": "",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "76",
                "sip_profile_uuid": "1",
                "name": "tls-version",
                "value": "$${sip_tls_version}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "77",
                "sip_profile_uuid": "1",
                "name": "tls-ciphers",
                "value": "$${sip_tls_ciphers}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "78",
                "sip_profile_uuid": "1",
                "name": "tls-orq-connect-timeout",
                "value": "3000",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "79",
                "sip_profile_uuid": "1",
                "name": "rtp-autoflush-during-brsip_profile_uuidge",
                "value": "false",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "80",
                "sip_profile_uuid": "1",
                "name": "rtp-rewrite-timestamps",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "81",
                "sip_profile_uuid": "1",
                "name": "pass-rfc2833",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "82",
                "sip_profile_uuid": "1",
                "name": "odbc-dsn",
                "value": "dsn:user:pass",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "83",
                "sip_profile_uuid": "1",
                "name": "odbc-dsn",
                "value": "pgsql://hostaddr=127.0.0.1 dbname=freeswitch user=freeswitch password=\"\" options=\"-c client_min_messages=NOTICE\" application_name=\"freeswitch\"",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "84",
                "sip_profile_uuid": "1",
                "name": "odbc-dsn",
                "value": "mariadb://Server=192.168.1.88;Database=internal;Uid=freeswitch;Pwd=freeswitch;",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "85",
                "sip_profile_uuid": "1",
                "name": "db-spin-up-wait-ms",
                "value": "1000",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "86",
                "sip_profile_uuid": "1",
                "name": "inbound-bypass-media",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "87",
                "sip_profile_uuid": "1",
                "name": "inbound-proxy-media",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "88",
                "sip_profile_uuid": "1",
                "name": "inbound-late-negotiation",
                "value": "true",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "89",
                "sip_profile_uuid": "1",
                "name": "accept-blind-reg",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "90",
                "sip_profile_uuid": "1",
                "name": "accept-blind-auth",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "91",
                "sip_profile_uuid": "1",
                "name": "suppress-cng",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "92",
                "sip_profile_uuid": "1",
                "name": "nonce-ttl",
                "value": "60",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "93",
                "sip_profile_uuid": "1",
                "name": "disable-transcoding",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "94",
                "sip_profile_uuid": "1",
                "name": "manual-redirect",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "95",
                "sip_profile_uuid": "1",
                "name": "disable-transfer",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "96",
                "sip_profile_uuid": "1",
                "name": "disable-register",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "97",
                "sip_profile_uuid": "1",
                "name": "NDLB-broken-auth-hash",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "98",
                "sip_profile_uuid": "1",
                "name": "NDLB-received-in-nat-reg-contact",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "99",
                "sip_profile_uuid": "1",
                "name": "auth-calls",
                "value": "$${internal_auth_calls}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "100",
                "sip_profile_uuid": "1",
                "name": "auth-subscriptions",
                "value": "true",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "101",
                "sip_profile_uuid": "1",
                "name": "inbound-reg-force-matching-username",
                "value": "true",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "102",
                "sip_profile_uuid": "1",
                "name": "auth-all-packets",
                "value": "false",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "103",
                "sip_profile_uuid": "1",
                "name": "ext-rtp-ip",
                "value": "$${external_rtp_ip}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "104",
                "sip_profile_uuid": "1",
                "name": "ext-sip-ip",
                "value": "$${external_sip_ip}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "105",
                "sip_profile_uuid": "1",
                "name": "rtp-timeout-sec",
                "value": "300",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "106",
                "sip_profile_uuid": "1",
                "name": "rtp-hold-timeout-sec",
                "value": "1800",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "107",
                "sip_profile_uuid": "1",
                "name": "vad",
                "value": "in",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "108",
                "sip_profile_uuid": "1",
                "name": "vad",
                "value": "out",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "109",
                "sip_profile_uuid": "1",
                "name": "vad",
                "value": "both",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "110",
                "sip_profile_uuid": "1",
                "name": "alias",
                "value": "sip:10.0.1.251:5555",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "111",
                "sip_profile_uuid": "1",
                "name": "force-register-domain",
                "value": "$${domain}",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "112",
                "sip_profile_uuid": "1",
                "name": "force-subscription-domain",
                "value": "$${domain}",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "113",
                "sip_profile_uuid": "1",
                "name": "force-register-db-domain",
                "value": "$${domain}",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "114",
                "sip_profile_uuid": "1",
                "name": "ws-binding",
                "value": ":5066",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "115",
                "sip_profile_uuid": "1",
                "name": "wss-binding",
                "value": ":7443",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "116",
                "sip_profile_uuid": "1",
                "name": "delete-subs-on-register",
                "value": "false",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "117",
                "sip_profile_uuid": "1",
                "name": "inbound-reg-in-new-thread",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "118",
                "sip_profile_uuid": "1",
                "name": "rtcp-audio-interval-msec",
                "value": "5000",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "119",
                "sip_profile_uuid": "1",
                "name": "rtcp-vsip_profile_uuideo-interval-msec",
                "value": "5000",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "120",
                "sip_profile_uuid": "1",
                "name": "force-subscription-expires",
                "value": "60",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "121",
                "sip_profile_uuid": "1",
                "name": "sip-subscription-max-deviation",
                "value": "120",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "122",
                "sip_profile_uuid": "1",
                "name": "disable-transfer",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "123",
                "sip_profile_uuid": "1",
                "name": "disable-register",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "124",
                "sip_profile_uuid": "1",
                "name": "enable-3pcc",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "125",
                "sip_profile_uuid": "1",
                "name": "NDLB-force-rport",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "126",
                "sip_profile_uuid": "1",
                "name": "challenge-realm",
                "value": "auto_from",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "127",
                "sip_profile_uuid": "1",
                "name": "disable-rtp-auto-adjust",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "128",
                "sip_profile_uuid": "1",
                "name": "inbound-use-callsip_profile_uuid-as-uusip_profile_uuid",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "129",
                "sip_profile_uuid": "1",
                "name": "outbound-use-uusip_profile_uuid-as-callsip_profile_uuid",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "130",
                "sip_profile_uuid": "1",
                "name": "rtp-autofix-timing",
                "value": "false",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "131",
                "sip_profile_uuid": "1",
                "name": "pass-callee-sip_profile_uuid",
                "value": "false",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "132",
                "sip_profile_uuid": "1",
                "name": "auto-rtp-bugs",
                "value": "clear",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "133",
                "sip_profile_uuid": "1",
                "name": "disable-srv",
                "value": "false",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "134",
                "sip_profile_uuid": "1",
                "name": "disable-naptr",
                "value": "false",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "135",
                "sip_profile_uuid": "1",
                "name": "timer-T1",
                "value": "500",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "136",
                "sip_profile_uuid": "1",
                "name": "timer-T1X64",
                "value": "32000",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "137",
                "sip_profile_uuid": "1",
                "name": "timer-T2",
                "value": "4000",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "138",
                "sip_profile_uuid": "1",
                "name": "timer-T4",
                "value": "4000",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "139",
                "sip_profile_uuid": "1",
                "name": "auto-jitterbuffer-msec",
                "value": "60",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "140",
                "sip_profile_uuid": "1",
                "name": "renegotiate-codec-on-hold",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "141",
                "sip_profile_uuid": "1",
                "name": "auto-invite-100",
                "value": "false",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "142",
                "sip_profile_uuid": "1",
                "name": "odbc-dsn",
                "value": "mariadb://Server=192.168.1.88;Database=internal;Uid=solman;Pwd=password;",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": "2024-06-21 01:47:46",
                "updated_at": "2024-06-21 01:47:46"
              },
              {
                "id": "144",
                "sip_profile_uuid": "2",
                "name": "debug",
                "value": "0",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "145",
                "sip_profile_uuid": "2",
                "name": "shutdown-on-fail",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "146",
                "sip_profile_uuid": "2",
                "name": "sip-trace",
                "value": "no",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "147",
                "sip_profile_uuid": "2",
                "name": "sip-capture",
                "value": "no",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "148",
                "sip_profile_uuid": "2",
                "name": "rfc2833-pt",
                "value": "101",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "149",
                "sip_profile_uuid": "2",
                "name": "enable-rfc-5626",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "150",
                "sip_profile_uuid": "2",
                "name": "sip-port",
                "value": "$${external_sip_port}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "151",
                "sip_profile_uuid": "2",
                "name": "dialplan",
                "value": "XML",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "152",
                "sip_profile_uuid": "2",
                "name": "context",
                "value": "public",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "153",
                "sip_profile_uuid": "2",
                "name": "dtmf-duration",
                "value": "2000",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "154",
                "sip_profile_uuid": "2",
                "name": "inbound-codec-prefs",
                "value": "$${global_codec_prefs}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "155",
                "sip_profile_uuid": "2",
                "name": "outbound-codec-prefs",
                "value": "$${outbound_codec_prefs}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "156",
                "sip_profile_uuid": "2",
                "name": "hold-music",
                "value": "$${hold_music}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "157",
                "sip_profile_uuid": "2",
                "name": "rtp-timer-name",
                "value": "soft",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "158",
                "sip_profile_uuid": "2",
                "name": "enable-100rel",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "159",
                "sip_profile_uuid": "2",
                "name": "disable-srv503",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "160",
                "sip_profile_uuid": "2",
                "name": "local-network-acl",
                "value": "localnet.auto",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "161",
                "sip_profile_uuid": "2",
                "name": "manage-presence",
                "value": "false",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "162",
                "sip_profile_uuid": "2",
                "name": "dbname",
                "value": "share_presence",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "163",
                "sip_profile_uuid": "2",
                "name": "presence-hosts",
                "value": "$${domain}",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "164",
                "sip_profile_uuid": "2",
                "name": "force-register-domain",
                "value": "$${domain}",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "165",
                "sip_profile_uuid": "2",
                "name": "force-register-db-domain",
                "value": "$${domain}",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "166",
                "sip_profile_uuid": "2",
                "name": "odbc-dsn",
                "value": "mariadb://Server=192.168.1.88;Database=external;Uid=solman;Pwd=password;",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "167",
                "sip_profile_uuid": "2",
                "name": "aggressive-nat-detection",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "168",
                "sip_profile_uuid": "2",
                "name": "inbound-codec-negotiation",
                "value": "generous",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "169",
                "sip_profile_uuid": "2",
                "name": "nonce-ttl",
                "value": "60",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "170",
                "sip_profile_uuid": "2",
                "name": "auth-calls",
                "value": "false",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "171",
                "sip_profile_uuid": "2",
                "name": "inbound-late-negotiation",
                "value": "true",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "172",
                "sip_profile_uuid": "2",
                "name": "rtp-ip",
                "value": "$${local_ip_v4}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "173",
                "sip_profile_uuid": "2",
                "name": "sip-ip",
                "value": "$${local_ip_v4}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "174",
                "sip_profile_uuid": "2",
                "name": "ext-rtp-ip",
                "value": "$${external_rtp_ip}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "175",
                "sip_profile_uuid": "2",
                "name": "ext-sip-ip",
                "value": "$${external_sip_ip}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "176",
                "sip_profile_uuid": "2",
                "name": "rtp-timeout-sec",
                "value": "300",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "177",
                "sip_profile_uuid": "2",
                "name": "rtp-hold-timeout-sec",
                "value": "1800",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "178",
                "sip_profile_uuid": "2",
                "name": "enable-3pcc",
                "value": "true",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "179",
                "sip_profile_uuid": "2",
                "name": "tls",
                "value": "$${external_ssl_enable}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "180",
                "sip_profile_uuid": "2",
                "name": "tls-only",
                "value": "false",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "181",
                "sip_profile_uuid": "2",
                "name": "tls-bind-params",
                "value": "transport=tls",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "182",
                "sip_profile_uuid": "2",
                "name": "tls-sip-port",
                "value": "$${external_tls_port}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "183",
                "sip_profile_uuid": "2",
                "name": "tls-cert-dir",
                "value": "",
                "enabled": "0",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "184",
                "sip_profile_uuid": "2",
                "name": "tls-passphrase",
                "value": "",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "185",
                "sip_profile_uuid": "2",
                "name": "tls-verify-date",
                "value": "true",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "186",
                "sip_profile_uuid": "2",
                "name": "tls-verify-policy",
                "value": "none",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "187",
                "sip_profile_uuid": "2",
                "name": "tls-verify-depth",
                "value": "2",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "188",
                "sip_profile_uuid": "2",
                "name": "tls-verify-in-subjects",
                "value": "",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "189",
                "sip_profile_uuid": "2",
                "name": "tls-version",
                "value": "$${sip_tls_version}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              },
              {
                "id": "190",
                "sip_profile_uuid": "2",
                "name": "tls-ciphers",
                "value": "$${sip_tls_ciphers}",
                "enabled": "1",
                "description": null,
                "created_by": null,
                "deleted_at": null,
                "created_at": null,
                "updated_at": null
              }
            ]
        }';

        // Convert JSON data to PHP associative array
        $arrayData = json_decode($jsonData, true);

        $data = $arrayData['data'];

        if ($arrayData === null) {
            echo "JSON decoding error: " . json_last_error_msg();
        }

        $formattedData = [];

        foreach ($data as $row) {
            unset($row['id'], $row['created_by'], $row['deleted_at'], $row['created_at'], $row['updated_at']);
            $row['created_at'] = date("Y-m-d H:i:s");
            $row['updated_at'] = date("Y-m-d H:i:s");
            $formattedData[] = $row;
        }

        SipProfileSetting::insert($formattedData);
    }
}
